services:
  test-app:
    container_name: stac-fastapi-geoparquet
    build: .
    environment:
      - STAC_FASTAPI_VERSION=0.1
      - STAC_FASTAPI_TITLE=CLOUD-NES datasets on SURF
      - STAC_FASTAPI_DESCRIPTION=A STAC API of the datasets hosted on SURF via the CLOUD-NES project
      - STAC_FASTAPI_LANDING_ID=cloud-nes
      - STAC_FASTAPI_COLLECTIONS_HREF=/data/collections.json
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/data:ro

  app:
    extends:
      service: test-app
    environment:
      - ROOT_PATH=/stac/v1
      - UVICORN_ROOT_PATH=/stac/v1
      - UVICORN_FORWARDED_ALLOW_IP=*
      - UVICORN_PROXY_HEADERS=true

networks:
  default:
    name: stac-fastapi-network
